### ISSUE TITLE
Create routes to shell mappings using JSON

### ISSUE THREAD

**Issue by carlskii** [msoap/shell2http#93]
Hi, wondering if there's a way to feed in the route & commands via JSON file or JSON on an HTTP endpoint?  I would like to use values stored in a db to create the mappings if possible.

**Comment by msoap** [comment]
Hi @carlskii,
json is not the best format for configuring routes because there will be difficulties with escaping quotes of different types, single and double, something like:
```
{"/path": "sh -c \"echo \\"hello\\"\""}
```
there i'm not sure that correct quotes or not

but just shell-file can be as a way to configure routes/commands, like:

**run_server.sh**:
```shell
#!/bin/sh
shell2http -port 8000 \
  /date date \
  /route1 "sh -c 'echo 123'" \
  /route2 "some_shell_script.sh"
```

this could almost be a replacement for json
